language: node_js
sude: required
node_js:
  - "4"
jdk:
  - oraclejdk8
addons:
  sonarqube: true
env:
  global:
    - secure: "LEqNyAdOhvgonqUWWyc+q9Adr38pnjr4z98p06OG08GpkBNo/IxdeYe452S1n1H0iZYC+Zj4JmUcZgV3u9FaZbvkK8VtRLnZTqvsHlIdcpnzfnsXnQNON1fLzcSbzG4TjazB/xlp5rRGLqD0eGAC2776sUvA701l97y2pMdxbcqAjKLdXWbdbXOg5FvPGkUQCOg6OdNDPudsxPuEfjOJ8DuHT8iN31CX506wau6BRotEzoMQBTKOY+/58BW+CkkT6h6EMHcbYvsjyt7OWFRzohQ8ulnUsNWD1cbqgOfZNt07/R9/4XceXyAyvk/uMwnSzbSo+aaBCbTemlpQByCLa8Z5YAw+CTup57DDveyB9D+aYa2vw6Bg+PaZfXEaeWitIvR5nJMVbtTGq10emxLKzDljXk/lWnu+2EXBG0kU/ddt68FRIK0dmnPs2KZBWXlxB2+LisDFZthosKgkzfQYj8kTp4BhCCq6a3kI35tOsi1WAXNUyReXZlZ2RZhI2C9X4y+k9ZZbd9n0NoYHAr0JqGn2GhVaUFGN8fHtdyGAZVKamDlcl9faYBkKl4w7bPJdA3TulCCdzXNAZNQkGPmqDMA9+XpPKDcfXfHhXucmIp0/60dKspxYG/RkQVb07oWOkm6tqzhYFZ8+D7kWkEre2Oi9xwHFpPY6AMBAbRgYZCk="
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sudo apt-get install oracle-java8-installer
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
