language: node_js
node_js:
  - "4"
jdk:
  - oraclejdk8
addons:
  sonarqube: true
  addons:
    apt:
      packages:
        - oraclejdk8
env:
  global:
    - secure: "C1zaivQpt8fxmHrEljW/YCjwkGaxcBwiiP4kNN8MVOIJFUPunNxaVdhRSrOSp//iFibux1cxKs2z6ip8gO8b9CXgrO5XRapcRndpb9ckz7l1dM1qgZNBeEFsm0PkOPtEyBKlxJrSg97Rog6xoSdole5p/ckwK1OOvtqcHxX+Zvq5kevbxRXUnRlN8CMPPq0ogt1pRDS8WdA17KYC7tDJ7FeIozCMlYIYFeY/eK73G117QXDCskD787bpecKUXlZWbSv6XNbpZmaLOc8l8na/0yQ3oMAzo2LkNCoGC2Bp6NU0xSS+VU8IBrSTWGh7fVSwVLXXIOX2uIUG2ow1KmdnEr7C3UlaFJXwo9UPg5Q4Vjdu3/KdpoGfCHbZqNeoxpJvt+wguFaAIONHbpe33KFgUYi3vCcQyU/vy2Enp7sBbGK6jXUb4mjeQg8N0xkNxKDLLTNSAECyGMPtxYQKoizv5Xhq8xkBuQm4aAgETFIzQsb5UE23HP89beyCn5TrbeLkXtw1u6859HZ+CCbn/m8YjaliQyFx7RBfXJMJne8RDdplA6vI08UMEZO40Rei/Wd2YSp67XqRmhxkHxZlMPqGTfniYTtqGIwcMdy7yAOIZBeFiTP3DpqxYITfRCDIciCq/yaKtPXTs0g7ClHxiwcQuxSLz7tx50Odpg8rYCnHFcI=" # defines SONAR_TOKEN=abcdef0123456789
script:
  # other script steps might be done before running the actual SonarQube analysis
  - update-alternatives --display java
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
