language: node_js
sudo: required
node_js:
  - '4'
addons:
  code_climate:
    repo_token:
      secure: "WdisaPhC9fQ/OhzL5VbQyzHME1M7fE3e0wDBAMHV0kTwAVFtdd6GTA/AW4bNdjjK951eHX2g0JPk0pJE5hKZTzHc+7LxtvNJSEJJCFG2EPtOaveH/voMcJJiLAdiSgmU9I1AMM4FE8fdwGNLBHs9vwE3O7Z4oW0KFGWBG5yasyWKhh1SWp2ZniNvP7H7GB2BGMruVCCebIYrIgJDnHb1tlW0TXRO8y7KJq4n41yRrp3dZP/pBTeb4vlKJX6vz7opyhHQbR5dh4U3x88Ab9wMYAz+8HQjrRV0rrPsGpy/1Na8L2CtpaRFGvr+TtLpbd3c3FIHz+rYvRRVk7kmbJnwR7Is8aAi1ZW6xNz4YSJqILC8z22Z4JIg8rXh3JA6Wm9aivHRdUK9PRhevoXla9pCL+da2XFcLQ6XPOCj4yC8h2Jr+1S+4gJ05DBmQAxru+ReRXe9CYXVRYPXbG1lYkU+JJ9D7eYKiV6R5txod2z4iAP11ytI3p1yVJgIZF8LCxEN8WFmaaDvt9G5UZhGvacRO5Szf+8BdX5ET2zGdvLZcC5KH2fKvXpZewqQwfhBIdOE1iKPqSLeGQrjSlLmNu8qtb77+PoTDTeV2Qi//1Ou22czCf0zQ/+zBpNslNtN1L+gWVfm1YJaoyaGHaGFwS9RqHfW2FATTnls6ivKm+m5++A="
after_script:
  - ls -al coverage
  - ls -al coverage/PhantomJS 2.1.1 (Linux 0.0.0)
  - ls -al coverage/PhantomJS\ 2.1.1\ (Linux\ 0.0.0)
  - codeclimate-test-reporter < ./coverage/PhantomJS 2.1.1 (Linux 0.0.0)/lcov.info
  - codeclimate-test-reporter < ./coverage/PhantomJS\ 2.1.1\ (Linux\ 0.0.0)/lcov.info
  - codeclimate-test-reporter < ./coverage/**/lcov.info
# Disable Sonar specific config - cannot get the authentication for uploading reports to work
#jdk:
#- oraclejdk8
#addons:
#  sonarqube: true
#env:
#  global:
#  - secure: NNVv9UI3ZDE50jROILRSWacjBhhsm9cqPnENETougLEr2G5kpBTRk1tTQivg5HNVYl1e0XsE+XwwRHyXC8v+M5g1sa/M3PUVVozp9gea6XREq0fInV4kwjCRmix0b7dIvsghqkCSJ0dRCbutKip4o65HmDoVcp93S+wiYn6YsvT6oQrFt3/pop+fxdwI0MtoQoW50E6XlGHMk7/p0RD7HYhR8ispOsrg6tRyO1RRH20fYUzC6U/IeUFww8IU10vY03ScTggcNqpJX+86WEZSJs6vsflSZhzwTs4ZQC5CcjBZMEMwS4l1K7q+TypYB1Knmg3FBS+C2zVhCUEAQK9Sl8utpx9BIhLuDrOIpiY//Aiz2+SkXRH45QbkX8NKJkZNnf2kmblcoCOREt79j4iK22JZYSJQEvfJNpffbj7Vrthc7Z+Tj6F+R09sdpT9AZzGHmxe53ZYEP5/9CMVQmBL4G7kaJwhcR1EFTDS1/zftPJt8ISABgPpuyMuQVu2PTFkQhhamNy0ihuqBc/IrsOcrV39XWdkwwzMXS+FSXcdJHxIs1pnJdmTjXgBxcYAXPPuZVt+gbN2L+sYIffOIxnQk6r55bTStoax33SgGWfqSBq5nAeZkYvuaQ0nqK/FgSHlAYG+VPzirV0GEku/XNxuLV6DE9+7/FjHFGmruD6zQyQ=
#script:
#- sudo apt-get install oracle-java8-installer
#- export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
#- sonar-scanner -Dsonar.login=$SONAR_TOKEN -e -X
